# ElasticSearchConnector defines settings related to ElasticSearch such as login information or URL
[ElasticSearchConnector]
    URL        = "http://localhost:9200"
    Username   = ""
    Password   = ""
